apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark-genius
  namespace: benchmark
  labels:
    app: benchmark-genius
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benchmark-genius
  template:
    metadata:
      labels:
        app: benchmark-genius
    spec:
      containers:
      - name: benchmark-genius
        image: 10.0.1.224:5000/benchmark-genius:latest
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: DEBUG
          value: "False"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: benchmark-genius-service
  namespace: benchmark
spec:
  type: NodePort
  selector:
    app: benchmark-genius
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30080
