# Prometheus + Node Exporter Monitoring Stack
# Namespace: benchmark
# Services exposed via NodePort:
# - Prometheus: 30090
# - Node Exporter: 31008
# RBAC: Cluster-wide access for both Prometheus and Node Exporter to access all pods

---
# ServiceAccount: Prometheus
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-sa
  namespace: benchmark

---
# ServiceAccount: Node Exporter
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-exporter-sa
  namespace: benchmark

---
# ClusterRole: Full access to pods, services, endpoints, and nodes for monitoring
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoring-cluster-access
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "endpoints", "nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch"]

---
# ClusterRoleBinding: Prometheus
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-cluster-access
subjects:
- kind: ServiceAccount
  name: prometheus-sa
  namespace: benchmark
roleRef:
  kind: ClusterRole
  name: monitoring-cluster-access
  apiGroup: rbac.authorization.k8s.io

---
# ClusterRoleBinding: Node Exporter
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-exporter-cluster-access
subjects:
- kind: ServiceAccount
  name: node-exporter-sa
  namespace: benchmark
roleRef:
  kind: ClusterRole
  name: monitoring-cluster-access
  apiGroup: rbac.authorization.k8s.io

---
# ConfigMap: Prometheus Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: benchmark
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      # Scrape Prometheus itself
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      
      # Scrape Node Exporter
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter:9100']

---
# Deployment: Node Exporter
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-exporter
  namespace: benchmark
  labels:
    app: node-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      serviceAccountName: node-exporter-sa
      containers:
      - name: node-exporter
        image: 10.0.1.224:5000/node-exporter:v1.7.0
        imagePullPolicy: Always
        ports:
        - containerPort: 9100
          name: metrics
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

---
# Service: Node Exporter (NodePort)
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: benchmark
  labels:
    app: node-exporter
spec:
  type: NodePort
  selector:
    app: node-exporter
  ports:
  - port: 9100
    targetPort: 9100
    nodePort: 31008
    name: metrics

---
# Deployment: Prometheus
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: benchmark
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus-sa
      containers:
      - name: prometheus
        image: 10.0.1.224:5000/prometheus:v2.48.0
        imagePullPolicy: Always
        args:
          - '--config.file=/etc/prometheus/prometheus.yml'
          - '--storage.tsdb.path=/prometheus'
          - '--web.console.libraries=/usr/share/prometheus/console_libraries'
          - '--web.console.templates=/usr/share/prometheus/consoles'
        ports:
        - containerPort: 9090
          name: web
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
        - name: prometheus-storage
          mountPath: /prometheus
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
      - name: prometheus-storage
        emptyDir: {}

---
# Service: Prometheus (NodePort)
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: benchmark
  labels:
    app: prometheus
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30090
    name: web
