
apiVersion: "clickhouse.altinity.com/v1"
kind: ClickHouseInstallation
metadata:
  name: clickhouse-single
  namespace: l1-app-ai
spec:
  configuration:
    clusters:
      - name: clickhouse
        layout:
          shardsCount: 1
          replicasCount: 1
    users:
      default/password: "defaultpass"
      default/networks/ip:
        - 0.0.0.0/0
