apiVersion: v1
kind: Pod
metadata:
  name: node-python-app
  namespace: l1-app-ai
spec:
  containers:
    - name: node-python-app
      image: l1-app-ai/node-python
      ports:
        - containerPort: 3000
      envFrom:
        - secretRef:
            name: l1-app-secret
  imagePullSecrets:
    - name: l1-app-secret