apiVersion: v1
kind: ServiceAccount
metadata:
  name: ricxapp-esxapp-sa
  namespace: ricxapp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ricxapp-pod-manager
  namespace: ricxapp
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ricxapp-pod-manager-binding
  namespace: ricxapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ricxapp-pod-manager
subjects:
- kind: ServiceAccount
  name: ricxapp-esxapp-sa
  namespace: ricxapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ricxapp-esxapp
  namespace: ricxapp
  labels:
    app: ricxapp-esxapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ricxapp-esxapp
  template:
    metadata:
      labels:
        app: ricxapp-esxapp
    spec:
      serviceAccountName: ricxapp-esxapp-sa
      containers:
      - name: energy-app
        image: 10.0.1.224:5000/ricxapp-esxapp:latest
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OLLAMA_HOST
          value: "http://ollama-service:11434"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - python
            - -c
            - "import sys; sys.exit(0)"
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - python
            - -c
            - "import sys; sys.exit(0)"
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ricxapp-esxapp-service
  namespace: ricxapp
spec:
  selector:
    app: ricxapp-esxapp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
