
---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: l1-app
  labels:
    name: l1-app
    purpose: l1-troubleshooting-platform
---
# ClickHouse PVC - using default storage class
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-pvc
  namespace: l1-app
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
---
# ClickHouse Deployment - OpenShift default security context
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  namespace: l1-app
  labels:
    app: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      initContainers:
      - name: setup-clickhouse-dirs
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          mkdir -p /var/lib/clickhouse/data
          mkdir -p /var/lib/clickhouse/logs
          mkdir -p /var/lib/clickhouse/tmp
          mkdir -p /var/lib/clickhouse/user_files
          mkdir -p /var/lib/clickhouse/access
          chmod -R 777 /var/lib/clickhouse
        volumeMounts:
        - name: clickhouse-data
          mountPath: /var/lib/clickhouse
        securityContext:
          runAsUser: 0
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:23.8
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 9000
          protocol: TCP
        - name: native
          containerPort: 9000
          protocol: TCP
        env:
        - name: CLICKHOUSE_DB
          value: "l1_anomaly_detection"
        - name: CLICKHOUSE_USER
          value: "default"
        - name: CLICKHOUSE_PASSWORD
          value: ""
        - name: CLICKHOUSE_DO_NOT_CHOWN
          value: "1"
        - name: CLICKHOUSE_UID
          value: "1001"
        - name: CLICKHOUSE_GID
          value: "1001"
        volumeMounts:
        - name: clickhouse-data
          mountPath: /var/lib/clickhouse
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /ping
            port: 9000
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /ping
            port: 9000
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: clickhouse-data
        persistentVolumeClaim:
          claimName: clickhouse-pvc
---
# ClickHouse Service
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-service
  namespace: l1-app
  labels:
    app: clickhouse
spec:
  selector:
    app: clickhouse
  ports:
  - name: http
    protocol: TCP
    port: 9000
    targetPort: 9000
  - name: native
    protocol: TCP
    port: 9000
    targetPort: 9000
  type: ClusterIP
