
apiVersion: v1
kind: ConfigMap
metadata:
  name: l1-app-config
data:
  NODE_ENV: "production"
  PORT: "5000"
  CLICKHOUSE_URL: "http://clickhouse-service:8123"
  CLICKHOUSE_DATABASE: "l1_anomaly_detection"
  CLICKHOUSE_USER: "default"
  CLICKHOUSE_PASSWORD: ""
  TSLAM_REMOTE_HOST: "10.193.0.4"
  TSLAM_REMOTE_PORT: "8080"
---
apiVersion: v1
kind: Secret
metadata:
  name: l1-app-secrets
type: Opaque
data:
  # Add any sensitive data here (base64 encoded)
  database_password: ""
