
apiVersion: apps/v1
kind: Deployment
metadata:
  name: l1-troubleshooting
  namespace: l1-app
  labels:
    app: l1-troubleshooting
spec:
  replicas: 2
  selector:
    matchLabels:
      app: l1-troubleshooting
  template:
    metadata:
      labels:
        app: l1-troubleshooting
    spec:
      containers:
      - name: l1-app
        image: node:18-alpine
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: NODE_ENV
          value: "production"
        - name: CLICKHOUSE_URL
          value: "http://clickhouse-service.l1-app.svc.cluster.local:8123"
        - name: CLICKHOUSE_HOST
          value: "clickhouse-service.l1-app.svc.cluster.local"
        - name: CLICKHOUSE_PORT
          value: "8123"
        - name: CLICKHOUSE_DATABASE
          value: "l1_anomaly_detection"
        - name: CLICKHOUSE_USER
          value: "default"
        - name: CLICKHOUSE_USERNAME
          value: "default"
        - name: CLICKHOUSE_PASSWORD
          value: ""
        - name: TSLAM_REMOTE_HOST
          value: "10.193.0.4"
        - name: TSLAM_REMOTE_PORT
          value: "8080"
        - name: JUPYTER_SERVICE_URL
          value: "http://jupyter-service.l1-app.svc.cluster.local:8888"
        command: ["/bin/sh"]
        args: ["-c", "npm install && npm run build && npm start"]
        workingDir: /app
        volumeMounts:
        - name: app-code
          mountPath: /app
        - name: shared-data
          mountPath: /app/shared
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: app-code
        configMap:
          name: l1-app-code
      - name: shared-data
        persistentVolumeClaim:
          claimName: shared-data-pvc
