
---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: l1-app-ns
  labels:
    name: l1-app-ns
    purpose: l1-troubleshooting-platform
---
# L1 Application ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: l1-app-config
  namespace: l1-app-ns
data:
  NODE_ENV: "production"
  PORT: "5000"
  CLICKHOUSE_URL: "http://clickhouse-service.l1-app-ns.svc.cluster.local:9000"
  CLICKHOUSE_HOST: "clickhouse-service.l1-app-ns.svc.cluster.local"
  CLICKHOUSE_PORT: "9000"
  CLICKHOUSE_DATABASE: "l1_anomaly_detection"
  CLICKHOUSE_USER: "default"
  CLICKHOUSE_USERNAME: "default"
  CLICKHOUSE_PASSWORD: ""
---
# L1 Application Secrets
apiVersion: v1
kind: Secret
metadata:
  name: l1-app-secrets
  namespace: l1-app-ns
type: Opaque
data:
  database_password: ""
  jwt_secret: bDEtYXBwLWp3dC1zZWNyZXQ=
---
# ClickHouse PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-pvc
  namespace: l1-app-ns
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
---
# L1 Application Data PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: l1-app-data-pvc
  namespace: l1-app-ns
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
---
# ClickHouse Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  namespace: l1-app-ns
  labels:
    app: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      initContainers:
      - name: setup-clickhouse-dirs
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          mkdir -p /var/lib/clickhouse/data
          mkdir -p /var/lib/clickhouse/logs
          mkdir -p /var/lib/clickhouse/tmp
          mkdir -p /var/lib/clickhouse/user_files
          mkdir -p /var/lib/clickhouse/access
          chmod -R 777 /var/lib/clickhouse
        volumeMounts:
        - name: clickhouse-data
          mountPath: /var/lib/clickhouse
        securityContext:
          runAsUser: 0
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:23.8
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 9000
        - name: tcp
          containerPort: 9000
        env:
        - name: CLICKHOUSE_DB
          value: "l1_anomaly_detection"
        - name: CLICKHOUSE_USER
          value: "default"
        - name: CLICKHOUSE_PASSWORD
          value: ""
        - name: CLICKHOUSE_DO_NOT_CHOWN
          value: "1"
        - name: CLICKHOUSE_UID
          value: "1001"
        - name: CLICKHOUSE_GID
          value: "1001"
        volumeMounts:
        - name: clickhouse-data
          mountPath: /var/lib/clickhouse
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /ping
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ping
            port: 9000
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: clickhouse-data
        persistentVolumeClaim:
          claimName: clickhouse-pvc
---
# ClickHouse Service
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-service
  namespace: l1-app-ns
  labels:
    app: clickhouse
spec:
  selector:
    app: clickhouse
  ports:
  - name: http
    protocol: TCP
    port: 9000
    targetPort: 9000
  - name: tcp
    protocol: TCP
    port: 9000
    targetPort: 9000
  type: ClusterIP
---
# L1 Application BuildConfig
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: l1-app-build
  namespace: l1-app-ns
  labels:
    app: l1-troubleshooting
spec:
  source:
    type: Git
    git:
      uri: https://github.com/your-repo/l1-troubleshooting.git
      ref: main
    contextDir: "."
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: l1-troubleshooting:latest
  triggers:
  - type: ConfigChange
  - type: GitHub
    github:
      secret: webhook-secret-l1
---
# L1 Application ImageStream
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: l1-troubleshooting
  namespace: l1-app-ns
  labels:
    app: l1-troubleshooting
spec:
  lookupPolicy:
    local: false
---
# L1 Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: l1-troubleshooting
  namespace: l1-app-ns
  labels:
    app: l1-troubleshooting
    version: v1.0.0
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: l1-troubleshooting
  template:
    metadata:
      labels:
        app: l1-troubleshooting
        version: v1.0.0
    spec:
      containers:
      - name: l1-app
        image: image-registry.openshift-image-registry.svc:5000/l1-app-ns/l1-troubleshooting:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: l1-app-config
              key: PORT
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: l1-app-config
              key: NODE_ENV
        - name: CLICKHOUSE_URL
          valueFrom:
            configMapKeyRef:
              name: l1-app-config
              key: CLICKHOUSE_URL
        - name: CLICKHOUSE_HOST
          valueFrom:
            configMapKeyRef:
              name: l1-app-config
              key: CLICKHOUSE_HOST
        - name: CLICKHOUSE_PORT
          valueFrom:
            configMapKeyRef:
              name: l1-app-config
              key: CLICKHOUSE_PORT
        - name: CLICKHOUSE_DATABASE
          valueFrom:
            configMapKeyRef:
              name: l1-app-config
              key: CLICKHOUSE_DATABASE
        - name: CLICKHOUSE_USER
          valueFrom:
            configMapKeyRef:
              name: l1-app-config
              key: CLICKHOUSE_USER
        - name: CLICKHOUSE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: l1-app-config
              key: CLICKHOUSE_USERNAME
        - name: CLICKHOUSE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: l1-app-config
              key: CLICKHOUSE_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: l1-app-secrets
              key: jwt_secret
        volumeMounts:
        - name: app-data
          mountPath: /app/data
        - name: tmp-storage
          mountPath: /tmp
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        startupProbe:
          httpGet:
            path: /health
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
          successThreshold: 1
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: l1-app-data-pvc
      - name: tmp-storage
        emptyDir:
          sizeLimit: 1Gi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
# L1 Application Service
apiVersion: v1
kind: Service
metadata:
  name: l1-troubleshooting-service
  namespace: l1-app-ns
  labels:
    app: l1-troubleshooting
spec:
  selector:
    app: l1-troubleshooting
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
  - name: https
    protocol: TCP
    port: 443
    targetPort: 5000
  type: ClusterIP
---
# L1 Application Route
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: l1-troubleshooting-route
  namespace: l1-app-ns
  labels:
    app: l1-troubleshooting
  annotations:
    haproxy.router.openshift.io/timeout: 300s
    haproxy.router.openshift.io/balance: roundrobin
spec:
  to:
    kind: Service
    name: l1-troubleshooting-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
---
# HorizontalPodAutoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: l1-troubleshooting-hpa
  namespace: l1-app-ns
  labels:
    app: l1-troubleshooting
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: l1-troubleshooting
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
