
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  namespace: l1-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: fast-ssd
---
