apiVersion: v1
kind: Pod
metadata:
  name: tslam-container
  namespace: l1-app-ai
  labels:
    app: tslam-container
spec:
  containers:
    - name: tslam-server
      image: 10.0.1.224:5000/tslam-with-model:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 8000
      env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: TRANSFORMERS_OFFLINE
          value: "0"
        - name: HF_HUB_DISABLE_SYMLINKS_WARNING
          value: "1"
        - name: TOKENIZERS_PARALLELISM
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: tslam-vllm-service
  namespace: l1-app-ai
spec:
  selector:
    app: tslam-container
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
