---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tslam-container
  namespace: l1-app-ai
  labels:
    app: tslam-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tslam-container
  template:
    metadata:
      labels:
        app: tslam-container
    spec:
      containers:
      - name: tslam-server
        image: localhost:5000/tslam-with-model:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        resources:
          requests:
            memory: "8Gi"
            cpu: "4"
          limits:
            memory: "16Gi"
            cpu: "8"
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: TRANSFORMERS_OFFLINE
          value: "0"
        - name: HF_HUB_DISABLE_SYMLINKS_WARNING
          value: "1"
        - name: TOKENIZERS_PARALLELISM
          value: "false"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 300
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 180
          periodSeconds: 15
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: tslam-container-service
  namespace: l1-app-ai
  labels:
    app: tslam-container
spec:
  selector:
    app: tslam-container
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
